name: CI/CD Pipeline   # Name of the pipeline

on:
  push:
    branches: [ "main" ]     # Run pipeline when pushing to main
  pull_request:
    branches: [ "main" ]     # Run pipeline on PRs to main

permissions:
  contents: write
  packages: write

jobs:
  build:                     # First job: build & push image
    runs-on: ubuntu-latest   # Run on a GitHub-hosted Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Step 1: Pull repo code into runner

      - name: Set up Python 3.9
        uses: actions/setup-python@v4   # Step 2: Install Python
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |                           # Step 3: Install pip, deps, and pytest
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q || echo "No tests found, skipping"
        # Step 4: Run unit tests (skip gracefully if none exist)

      - name: Build Docker image
        run: docker build -t mlops_ci_cd_iris .
        # Step 5: Build Docker image from Dockerfile, tag as 'mlops_ci_cd_iris'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
        # Step 6: Configure AWS access keys stored in GitHub Secrets

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        # Step 7: Authenticate Docker to push to Amazon ECR

      - name: Tag and Push to ECR
        run: |                             # Step 8: Tag and push image to ECR repo
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=mlops_ci_cd_iris_reg
          IMAGE_TAG=latest
          docker tag mlops_ci_cd_iris:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG