name: CI Pipeline   # Name of the workflow

on:
  push:
    branches: [ "main" ]       # Trigger workflow when code is pushed to main branch
  pull_request:
    branches: [ "main" ]       # Also trigger when a PR is raised to main

permissions:
  contents: write   # Allows workflow to write to repo if needed
  packages: write   # Allows workflow to push Docker images/packages

jobs:
  build:                  # Define a job called 'build'
    runs-on: ubuntu-latest  # Run on a GitHub-hosted Ubuntu machine

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3   # Pulls the latest repo code into the runner

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"     # Installs Python 3.9 on the runner

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip    # Upgrade pip
          pip install -r requirements.txt        # Install project dependencies
          pip install pytest                     # Install pytest for testing

      # Step 4: Run tests
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q || echo "No tests found, skipping"
        # Runs unit tests; if none found, it skips instead of failing pipeline

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t mlops_ci_cd_iris .
        # Builds Docker image from Dockerfile in current directory
        # and tags it with the name 'mlops_ci_cd_iris